spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: testteasfjlasjfl123182739874397akjljsdfasdfasfwearqwe2345365373524gfadfdasdfasdf21324567afasdfasdfadft5fasdf


email:
  google:
    email: test@test.com
    password: asdfqwerzxcv

google:
  api:
    key: test-dummy-key
    find-place:
      url-prefix: http://test
      url-params: "&key="
    detail:
      url-prefix: http://test
      url-params: "&key="
    nearby-search:
      url: http://test
      field-mask: places.id

pharmacy:
  api:
    key: test-dummy-key
    url: http://test
